# version: '3.8'

# services:
#   redis:
#     image: redis:latest
#     container_name: redis_container
#     ports:
#       - "6379:6379"
#     restart: always

#   app:
#     build: .
#     container_name: go_app
#     depends_on:
#       - redis
#     ports:
#       - "8080:8080"
#     environment:
#       - REDIS_ADDR=redis:6379
#     restart: always

version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: jatin_dharaiya
      MONGO_INITDB_ROOT_PASSWORD: Jatin%4008102000

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    restart: always

  app:
    build: .
    container_name: go_app
    depends_on:
      - mongodb
      - redis
    ports:
      - "9090:9090"
    environment:
      - MONGO_URI=mongodb+srv://jatin_dharaiya:Jatin%4008102000@demo.havv7ft.mongodb.net/golang_api
      - REDIS_ADDR=redis:6379
    restart: always
